config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :orders do
      resources :invoices, only: [:index, :create]
    end

    resources :reports, only: [:index, :show] do
      collection do
        get :invoiced_total
        post :invoiced_total
      end
    end
  end

  resources :invoices, only: [:show]
end

app/models/spree/invoice.rb
require 'spree_invoices/invoice_pdf'

module Spree
  class Invoice < ActiveRecord::Base
    INVOICES_PATH = Rails.root.join 'invoices'

    after_create :create_pdf_file

    belongs_to :order
    belongs_to :parent_invoice, class_name: 'Spree::Invoice',
      foreign_key: 'parent_invoice_id'
    has_one :additional_invoice, class_name: 'Spree::Invoice'

    validates :order, presence: true

    default_scope { order created_at: :asc }

    def to_param
      "#{order.number}-#{id}"
    end

    def concept
      concept = if total < 0
                  "Abono factura anterior"
                else
                  "cargo adicional factura anterior"
                end
      concept << " (factura #{parent_invoice_id}), pedido #{order.number}"
    end

    def total_without_taxes
      total / (1 + vat_rate)
    end

    def create_pdf_file!
      create_pdf_file
    end
    private

    def create_pdf_file
      FileUtils.mkdir_p INVOICES_PATH
      filename = "#{self.order.number}-#{self.id}.pdf"
      pdf = SpreeInvoices::InvoicePdf.new(self)
      pdf.render_file Rails.root.join(INVOICES_PATH, filename)
      update_column :filename, filename
    end
  end
end

app/models/spree/invoices_configuration.rb
module Spree
  class InvoicesConfiguration < Preferences::Configuration

    preference :invoices_logo_path, :string, default: Spree::Config[:admin_interface_logo]
  end
end

app/models/spree/order_decorator.rb
module Spree
  Order.class_eval do
    has_many :invoices, dependent: :destroy

    register_update_hook :conditional_create_first_invoice

    def needs_additional_invoice?
      self.payment_state == 'paid' && (
        (self.invoices.one? && self.total != self.invoices.last.total) ||
        (self.invoices.count > 1 && invoices_total != self.total)
      )
    end

    def create_additional_invoice
      last_invoice = self.invoices.last
      inv_total = self.total - invoices_total

      self.invoices.create(
        total: inv_total,
        parent_invoice: last_invoice,
        vat_rate: vat_rate_for_invoices,
        tax_total: inv_total - (inv_total / (1 + vat_rate_for_invoices))
      )
    end

    def conditional_create_first_invoice
      if needs_first_invoice?
        self.invoices.create(total: self.total,
                             vat_rate: vat_rate_for_invoices,
                             shipment_without_taxes: self.shipment_total / (1 + vat_rate_for_invoices),
                             tax_total: self.included_tax_total)
      end
    end

    private

    def needs_first_invoice?
      self.state == 'complete' and self.payment_state == 'paid' and
        self.invoices.empty?
    end

    def invoices_total
      self.invoices.sum(&:total)
    end

    def vat_rate_for_invoices
      @vat_rate_for_invoices ||= self.tax_zone.tax_rates.first.amount
    end
  end
end

app/controllers/admin/reports_controller_decorator.rb
require 'csv'

module Spree
  module Admin
    ReportsController.class_eval do
      def initialize
        super
        ReportsController.add_available_report!(:invoiced_total)
        ReportsController.add_available_report!(:sales_total)
      end

      def invoiced_total
        params[:q] = {} unless params[:q]

        if params[:q][:created_at_gt].blank?
          params[:q][:created_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end

        if params[:q] && !params[:q][:created_at_lt].blank?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        end

        @search = Invoice.ransack(params[:q])
        @invoices = @search.result

        respond_to do |format|
          format.html
          format.csv do
            send_data generate_csv, filename: "facturacion_St_Honore.csv"
          end
        end
      end

      private

      def generate_csv
        CSV.generate do |csv|
          @invoices.each do |invoice|
            csv << [
              invoice.id,
              invoice.parent_invoice_id,
              invoice.order.number,
              invoice.order.email,
              invoice.total
            ]
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/invoices_controller.rb
module Spree
  module Admin
    class InvoicesController < ResourceController
      respond_to :html
      before_action :load_order

      def index
        @invoices = @order.invoices
      end

      def create
        @invoice = @order.create_additional_invoice

        redirect_to action: :index
      end

      private

      def load_order
        @order = Spree::Order.find_by(number: params[:order_id])
      end
    end
  end
end

app/controllers/spree/admin/reports_controller_decorator.rb
module Spree
  module Admin
    ReportsController.class_eval do
      def initialize
        super
        ReportsController.add_available_report!(:invoiced_total)
        ReportsController.add_available_report!(:sales_total)
      end

      def invoiced_total
        params[:q] = {} unless params[:q]

        if params[:q][:created_at_gt].blank?
          params[:q][:created_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end

        if params[:q] && !params[:q][:created_at_lt].blank?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        end

        @search = Invoice.ransack(params[:q])
        @invoices = @search.result
      end
    end
  end
end

app/controllers/spree/invoices_controller.rb
module Spree
  class InvoicesController < Spree::StoreController
    respond_to :html

    def show
      @invoice = Spree::Invoice.find(params[:id].split('-')[1])
      authorize! :read, @invoice

      @order = @invoice.order

      respond_with @invoice do |format|
        format.html do
          send_file Rails.root.join(Spree::Invoice::INVOICES_PATH, @invoice.filename)
        end
      end
    end
  end
end

app/views/spree/admin/invoices/index.html.erb
<% content_for :page_actions do %>
  <% if @order.needs_additional_invoice? and can? :create, Spree::Invoice %>
    <%== button_link_to Spree.t(:create_additional_invoice), [:admin, @order, Spree::Invoice.new], method: :post %>
  <% end %>
<% end %>

<%= render 'spree/admin/shared/order_tabs', :current => 'Invoices' %>
<table class="invoices index">
  <colgroup>
    <col style="width: 15%" />
    <col style="width: 50%" />
    <col style="width: 35%" />
  </colgroup>
  <thead>
    <tr>
      <th><%= Spree.t :invoice_number %></th>
      <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr class="invoice">
        <td class='align-center'><%= invoice.id %></td>
        <td class='align-center'><%= pretty_time(invoice.created_at) %></td>
        <td class='align-center'><%= link_to Spree.t(:download_invoice),
          invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/orders/_invoices_tab.html.erb
<li <%== ' class="active"' if (defined? current and current == 'Invoices') %>>
  <%= link_to_with_icon 'icon-file-alt', Spree.t(:invoices), admin_order_invoices_url(@order) %>
</li>

app/views/spree/admin/reports/invoiced_total.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:invoiced_total) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_reports_list), spree.admin_reports_url, :class => 'button' %></li>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:date_range) %>
<% end %>

<% content_for :table_filter do %>
  <%= render :partial => 'spree/admin/shared/report_invoices_criteria' %>
<% end %>

<% if @invoices.any? %>
  <%== button_link_to Spree.t(:download_csv_report),
    url_for(
      format: :csv,
      "q[created_at_gt]" => @invoices.first.created_at,
      "q[created_at_lt]" => @invoices.last.created_at)
  %>
<% end %>

<table class="admin-report" class="invoice-report">
  <thead>
    <tr>
      <th><%= Spree.t(:invoice_number) %></th>
      <th><%= Spree.t(:invoice_parent) %></th>
      <th><%= Spree.t(:order_number, number: nil) %></th>
      <th><%= Spree.t(:invoice_date) %></th>
      <th><%= Spree.t(:total) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr class="align-center">
        <td><%= invoice.id %></td>
        <td><%= invoice.parent_invoice_id %></td>
        <td><%= invoice.order.number %></td>
        <td><%= pretty_time invoice.created_at %></td>
        <td><%= invoice.total %></td>
        <td><%= link_to Spree.t(:download_invoice), invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/shared/_report_invoices_criteria.html.erb
<%= search_form_for @search, :url => spree.invoiced_total_admin_reports_path  do |s| %>
    <div class="date-range-filter field align-center">
        <%= label_tag nil, Spree.t(:start), :class => 'inline' %>
        <%= s.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => datepicker_field_value(params[:q][:created_at_gt]) %>

        <span class="range-divider">
          <i class="icon-arrow-right"></i>
        </span>

        <%= s.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => datepicker_field_value(params[:q][:created_at_lt]) %>
        <%= label_tag nil, Spree.t(:end), :class => 'inline' %>
    </div>

    <div class="actions filter-actions">
      <%= button Spree.t(:search), 'icon-search'  %>
    </div>
<% end %>

app/views/spree/orders/_download_invoice.html.erb
<% if @order.invoices.size == 1 and can? :read, @order.invoices.first and
  @order.payment_state == 'paid' %>
  <div style="margin-bottom: 18px;">
    <%= link_to Spree.t(:download_invoice), invoice_path(@order.invoices.first) %>
  </div>
<% end %>